# Fail2Ban filter for Xtream Codes API endpoints
[INCLUDES]
before = common.conf

[Definition]
# Cattura tutte le richieste a player_api.php o panel_api.php, escludendo quelle con azioni legittime
failregex = ^<HOST> -.*"(GET|POST) \/player_api\.php\?.* HTTP\/.*
            ^<HOST> -.*"(GET|POST) \/panel_api\.php\?.* HTTP\/.*

ignoreregex = ^192\.168\..*$
              ^10\..*$
              ^127\.0\.0\.1$
			        ^<HOST>.*"GET \/player_api.php\?username=.*&password=.*&action=.*
			        ^<HOST>.*"GET \/player_api.php\?action=.*

# Formato data standard di Nginx/Apache: [10/Oct/2025:14:23:01 +0200]
datepattern = \[%%d/%%b/%%Y:%%H:%%M:%%S %%z\]
